name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$KEY" > ~/.ssh/beget.key
          chmod 600 ~/.ssh/beget.key
          cat >>~/.ssh/config <<END

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        run: rsync -e "ssh -p 20022 -i ~/.ssh/KEY -o StrictHostKeyChecking=no" --archive --compress --delete . khilkons@khilkons.beget.tech:/home/k/khilkons/oleg-khilko.ru/public_html
