name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/beget.key
          chmod 700 ~/.ssh/beget.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy
        run: rsync -e "ssh -p 22 -i ~/.ssh/beget.key -o StrictHostKeyChecking=no" --archive --compress --delete . khilkons@khilkons.beget.tech:/home/k/khilkons/oleg-khilko.ru/public_html
